clinical trial:
    represented_as: node
    preferred_id: id
    input_label: study
    is_a: named thing
    properties:
        brief_title: str
        official_title: str
        status: str
        brief_summary: str
        detailed_description: str
        keywords: str[]
        phases: str
        study_type: str
        n_participants: int
        why_stopped: str
        trial2vec_emb: float[]
        biobert_emb: float[]

intervention:
    represented_as: node
    preferred_id: id
    input_label: intervention
    is_a: clinical intervention
    properties:
        name: str
        type: str
        mapped_names: str[]
        biobert_emb: float[]

# organisation:
#     represented_as: node
#     preferred_id: id
#     input_label: organisation
#     # is_a: administrative entity
#     properties:
#         name: str
#         class: str

# sponsor:
#     represented_as: node
#     input_label: sponsor
#     # is_a: administrative entity

outcome:
    represented_as: node
    preferred_id: id
    input_label: outcome
    is_a: clinical entity
    properties:
        primary: bool
        measure: str
        time_frame: str
        description: str
        biobert_emb: float[]

# outcome measure:
#     represented_as: node
#     preferred_id: id
#     input_label: outcome_measure
#     # is_a: clinical measurement
#     properties:
#         title: str
#         type: str
#         description: str

condition:
    represented_as: node
    preferred_id: id
    input_label: condition
    is_a: named thing
    synonym_for: disease
    properties:
        name: str
        biobert_emb: float[]

# location:
#     synonym_for: geographic location
#     represented_as: node
#     preferred_id: id
#     input_label: location
#     # is_a: missing
#     properties:
#         facility: str
#         country: str
#         state: str
#         city: str

eligibility:
    represented_as: node
    preferred_id: id
    input_label: eligibility
    is_a: study population
    properties:
        sex: str
        healthy_volunteers: bool
        minimum_age: str
        maximum_age: str
        standardised_ages: str[]
        eligibility_criteria: str

# biospec:
#     represented_as: node
#     preferred_id: id
#     input_label: biospec
#     # is_a: biosample
#     properties:
#         retention: str
#         description: str
#         biobert_emb: float[]

# arm group:
#     represented_as: node
#     preferred_id: id
#     input_label: arm_group
#     # is_a: study population
#     properties:
#         label: str
#         type: str
#         description: str

intervention protocol:
    represented_as: node
    preferred_id: id
    input_label: intervention_protocol
    is_a: publication
    properties:
        model: str
        description: str
        allocation: str
        masking: str[]
        masking_description: str

observation protocol:
    represented_as: node
    preferred_id: id
    input_label: observation_protocol
    is_a: publication
    properties:
        model: str
        time_perspective: str
        patient_registry: bool
        sampling_method: str

adverse event protocol:
    represented_as: node
    preferred_id: id
    input_label: adverse_event_protocol
    is_a: publication
    properties:
        description: str
        timeframe: str

adverse event:
    represented_as: node
    preferred_id: id
    input_label: adverse_event
    is_a: adverse_event_of
    properties:
        term: str
        biobert_emb: float[]

# adverse event group:
#     represented_as: node
#     preferred_id: id
#     input_label: adverse_event_group
#     # is_a: study population
#     properties:
#         title: str
#         description: str

organ system:
    represented_as: node
    preferred_id: id
    input_label: organ_system
    is_a: named thing
    properties:
        name: str
        biobert_emb: float[]

# clinicalTrial to condition:
#     is_a: association
#     represented_as: edge
#     input_label: study_has_condition
#     source: study
#     target: condition

condition to clinicalTrial association:
    is_a: association
    represented_as: edge
    input_label: condition_has_study
    source: condition
    target: study

# clinicalTrial to organisation association:
#     is_a: association
#     represented_as: edge
#     input_label: study_has_organisation
#     source: study
#     target: organisation

# organisation to clinicalTrial:
#     is_a: association
#     represented_as: edge
#     input_label: conducts
#     source: organisation
#     target: study

# clinicalTrial to intervention association:
#     is_a: association
#     represented_as: edge
#     input_label: study_has_intervention
#     source: study
#     target: intervention

intervention to clinicalTrial association:
    is_a: association
    represented_as: edge
    input_label: intervention_has_study
    source: intervention
    target: study

# intervention to arm group association:
#     is_a: association
#     represented_as: edge
#     input_label: intervention_has_arm
#     source: intervention
#     target: arm_group

clinicalTrial to outcome association:
    is_a: association
    represented_as: edge
    input_label: study_has_outcome
    source: study
    target: outcome

# clinicalTrial to location association:
#     is_a: association
#     represented_as: edge
#     input_label: conducted_at
#     source: study
#     target: location

# clinicalTrial to sponsor association:
#     is_a: association
#     represented_as: edge
#     input_label: study_has_sponsor
#     source: study
#     target: sponsor

# sponsor to clinicalTrial association:
#     is_a: association
#     represented_as: edge
#     input_label: sponsors
#     source: sponsor
#     target: study

# clinicalTrial to arm group association:
#     is_a: association
#     represented_as: edge
#     input_label: study_has_arm_group
#     source: study
#     target: arm_group

clinicalTrial to eligibility association:
    is_a: association
    represented_as: edge
    input_label: study_has_eligibility
    source: study
    target: eligibility

# clinicalTrial to biospec association:
#     is_a: association
#     represented_as: edge
#     input_label: study_has_biospec
#     source: study
#     target: eligibility

clinicalTrial to intervention protocol association:
    is_a: association
    represented_as: edge
    input_label: follows_intervention_protocol
    source: study
    target: intervention_protocol

clinicalTrial to observation protocol association:
    is_a: association
    represented_as: edge
    input_label: follows_observation_protocol
    source: study
    target: observation_protocol

clinicalTrial to adverse event protocol association:
    is_a: association
    represented_as: edge
    input_label: follows_adverse_event_protocol
    source: study
    target: adverse_event_protocol

clinicalTrial to adverse event association:
    is_a: association
    represented_as: edge
    input_label: study_has_adverse_event
    source: study
    target: adverse_event
    properties:
        serious_event: bool
        assessment_type: str
        organ_system: str
        notes: str
        stats: str

# adverse event to clinicalTrial association:
#     is_a: association
#     represented_as: edge
#     input_label: adverse_event_has_study
#     source: adverse_event
#     target: study
#     properties:
#         serious_event: bool
#         assessment_type: str
#         organ_system: str
#         notes: str
#         stats: str

adverse event to organ system association:
    is_a: association
    represented_as: edge
    input_label: adverse_event_has_organ_system
    source: adverse_event
    target: organ_system
# adverse event to adverse event group association:
#     is_a: association
#     represented_as: edge
#     input_label: adverse_event_has_adverse_event_group
#     source: adverse_event
#     target: adverse_event_group
#     properties:
#         num_events: int
#         num_affected: int
#         num_at_risk: int

# clinicalTrial to adverse event group association:
#     is_a: association
#     represented_as: edge
#     input_label: study_has_adverse_event_group
#     source: study
#     target: adverse_event_group

# clinicalTrial to adverse event group protocol association:
#     is_a: association
#     represented_as: edge
#     input_label: follows_adverse_event_group_protocol
#     source: study
#     target: adverse_event_group_protocol

# clinicalTrial to outcome_measure  association:
#     is_a: association
#     represented_as: edge
#     input_label: study_has_outcome_measure
#     source: study
#     target: outcome_measure
