# add your settings here (overriding the defaults)

biocypher:
  offline: true
  debug: true
  schema_config_path: ./src/knowlege_graph/biocypher_config/schema_config.yaml

neo4j:
  database_name: ctgov
  delimiter: '\t'
  array_delimiter: "|"
  quote_character: '"'
  skip_duplicate_nodes: true
  skip_bad_relationships: true
