clinical trial:
    represented_as: node
    preferred_id: id
    input_label: study
    properties:
        brief_title: str
        official_title: str
        status: str
        brief_summary: str
        detailed_description: str
        keywords: str[]
        phases: str
        study_type: str
        why_stopped: str
        trial2vec_emb: float[]

intervention:
    represented_as: node
    input_label: intervention
    is_a: clinical intervention
    properties:
        name: str
        type: str
        mapped_names: str[]
        trial2vec_emb: float[]
        biobert_emb: float[]

organisation:
    is_a: administrative entity
    represented_as: node
    input_label: organisation
    properties:
        name: str
        class: str

sponsor:
    is_a: administrative entity
    represented_as: node
    input_label: sponsor

outcome:
    is_a: clinical entity
    represented_as: node
    input_label: outcome
    properties:
        primary: bool
        measure: str
        timeframe: str
        description: str
        trial2vec_emb: float[]
        biobert_emb: float[]

outcome measure:
    is_a: clinical measurement
    represented_as: node
    input_label: outcome_measure
    properties:
        title: str
        type: str
        description: str

condition:
    represented_as: node
    input_label: condition
    synonym_for: disease
    properties:
        condition: str
        trial2vec_emb: float[]
        biobert_emb: float[]

location:
    synonym_for: geographic location
    represented_as: node
    input_label: location
    properties:
        facility: str
        country: str
        state: str
        city: str

eligibility:
    represented_as: node
    input_label: eligibility
    is_a: study population
    properties:
        sex: str
        healthy_volunteers: bool
        minimum_age: str
        maximum_age: str
        standardised_ages: str[]
        eligibility_criteria: str
        trial2vec_emb: float[]
        biobert_emb: float[]

biospec:
    represented_as: node
    input_label: biospec
    is_a: biosample
    properties:
        retention: str
        description: str
        trial2vec_emb: float[]
        biobert_emb: float[]

arm group:
    represented_as: node
    input_label: arm_group
    is_a: study population
    properties:
        label: str
        type: str
        description: str

intervention protocol:
    represented_as: node
    input_label: intervention_protocol
    is_a: publication
    properties:
        model: str
        description: str
        allocation: str
        masking: str[]
        masking_description: str

observation protocol:
    represented_as: node
    input_label: observation_protocol
    is_a: publication
    properties:
        model: str
        time_perspective: str
        patient_registry: bool
        sampling_method: str

adverse event:
    represented_as: node
    input_label: adverse_event
    is_a: adverse_event_of
    properties:
        term: str
        trial2vec_emb: float[]
        biobert_emb: float[]

adverse event group:
    represented_as: node
    input_label: adverse_event_group
    is_a: study population
    properties:
        title: str
        description: str

organ system:
    represented_as: node
    input_label: organ_system
    is_a: named thing
    properties:
        name: str
        trial2vec_emb: float[]
        biobert_emb: float[]

adverse event protocol:
    represented_as: node
    input_label: adverse_event_group_protocol
    is_a: publication
    properties:
        timeframe: str
        description: str

study to condition:
    is_a: association
    represented_as: edge
    input_label: study_has_condition
    source: study
    target: condition

condition to study:
    is_a: association
    represented_as: edge
    input_label: condition_has_study
    source: condition
    target: study

study to organisation:
    is_a: association
    represented_as: edge
    input_label: study_has_orgnisation
    source: study
    target: organisation

organisation to study:
    is_a: association
    represented_as: edge
    input_label: conducts
    source: organisation
    target: study

study to intervention association:
    is_a: association
    represented_as: edge
    input_label: study_has_intervention
    source: study
    target: intervention

intervention to study association:
    is_a: association
    represented_as: edge
    input_label: intervention_has_study
    source: intervention
    target: study

intervention to arm group association:
    is_a: association
    represented_as: edge
    input_label: intervention_has_arm
    source: intervention
    target: arm_group

study to outcome association:
    is_a: association
    represented_as: edge
    input_label: study_has_outcome
    source: study
    target: outcome

study to location association:
    is_a: association
    represented_as: edge
    input_label: conducted_at
    source: study
    target: location

study to sponsor association:
    is_a: association
    represented_as: edge
    input_label: study_has_sponsor
    source: study
    target: sponsor

sponsor to study association:
    is_a: association
    represented_as: edge
    input_label: sponsors
    source: sponsor
    target: study

study to arm group association:
    is_a: association
    represented_as: edge
    input_label: study_has_arm_group
    source: study
    target: arm_group

study to eligibility association:
    is_a: association
    represented_as: edge
    input_label: study_has_eligibility
    source: study
    target: eligibility

study to biospec association:
    is_a: association
    represented_as: edge
    input_label: study_has_biospec
    source: study
    target: eligibility

study to intervention protocol association:
    is_a: association
    represented_as: edge
    input_label: follows_intervention_protocol
    source: study
    target: intervention_protocol

study to observation protocol association:
    is_a: association
    represented_as: edge
    input_label: follows_observation_protocol
    source: study
    target: observation_protocol

study to adverse event protocol association:
    is_a: association
    represented_as: edge
    input_label: follows_adverse_event_protocol
    source: study
    target: adverse_event_protocol

study to adverse event association:
    is_a: association
    represented_as: edge
    input_label: study_has_adverse_event
    source: study
    target: adverse_event
    properties:
        serious_event: bool
        assessment_type: str
        organ_system: str
        notes: str
        stats: str

adverse event to study association:
    is_a: association
    represented_as: edge
    input_label: adverse_event_has_study
    source: adverse_event
    target: study
    properties:
        serious_event: bool
        assessment_type: str
        organ_system: str
        notes: str
        stats: str

adverse event to organ system association:
    is_a: association
    represented_as: edge
    input_label: adverse_event_has_organ_system
    source: adverse_event
    target: organ_system

adverse event to adverse event group association:
    is_a: association
    represented_as: edge
    input_label: adverse_event_has_adverse_event_group
    source: adverse_event
    target: adverse_event_group
    properties:
        num_events: int
        num_affected: int
        num_at_risk: int

study to adverse event group association:
    is_a: association
    represented_as: edge
    input_label: study_has_adverse_event_group
    source: study
    target: adverse_event_group

study to adverse event group protocol association:
    is_a: association
    represented_as: edge
    input_label: follows_adverse_event_group_protocol
    source: study
    target: adverse_event_group_protocol

study to outcome_measure  association:
    is_a: association
    represented_as: edge
    input_label: study_has_outcome_measure
    source: study
    target: outcome_measure
